export const dockerOverview = {
  host: {
    name: 'YesNAS Docker Host',
    engine: 'Docker Engine 27.4',
    uptime: '18 days 06:42',
    cpuUsage: 22,
    memoryUsage: 58,
    diskUsage: 39,
    networkDown: '59.54 MB/s',
    networkUp: '7.70 MB/s',
  },
  stats: [
    { id: 'cpu', label: 'CPU', value: '22%', detail: '6 cores available', tone: 'green' },
    { id: 'memory', label: 'RAM', value: '58%', detail: '18.6 / 32 GiB', tone: 'blue' },
    { id: 'network', label: 'Network', value: '59.5 MB/s', detail: 'Up 7.7 MB/s', tone: 'purple' },
    { id: 'disk', label: 'Docker Disk', value: '39%', detail: '780 / 2.0 TiB', tone: 'orange' },
  ],
}

export const dockerContainers = [
  {
    id: 'ct-jellyfin',
    name: 'jellyfin',
    image: 'jellyfin/jellyfin:latest',
    status: 'running',
    ports: ['8096:8096', '8920:8920'],
    cpu: 18,
    memory: 42,
    network: '12.4 MB/s',
    uptime: '9 days',
    color: 'from-indigo-500 to-blue-400',
    sparkline: [12, 18, 16, 28, 22, 30, 26, 38, 34, 42, 36, 40],
  },
  {
    id: 'ct-code-server',
    name: 'code-server',
    image: 'lscr.io/linuxserver/code-server',
    status: 'running',
    ports: ['8443:8443'],
    cpu: 9,
    memory: 28,
    network: '2.1 MB/s',
    uptime: '17 days',
    color: 'from-blue-500 to-cyan-400',
    sparkline: [6, 8, 10, 9, 16, 14, 18, 15, 17, 20, 16, 18],
  },
  {
    id: 'ct-mariadb',
    name: 'mariadb',
    image: 'mariadb:11',
    status: 'stopped',
    ports: ['3306:3306'],
    cpu: 0,
    memory: 0,
    network: '0 KB/s',
    uptime: 'stopped',
    color: 'from-slate-500 to-slate-700',
    sparkline: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    id: 'ct-redis',
    name: 'redis',
    image: 'redis:7-alpine',
    status: 'running',
    ports: ['6379:6379'],
    cpu: 3,
    memory: 12,
    network: '820 KB/s',
    uptime: '31 days',
    color: 'from-red-500 to-orange-400',
    sparkline: [4, 5, 4, 6, 5, 8, 7, 9, 6, 7, 8, 7],
  },
  {
    id: 'ct-libre-speed',
    name: 'librespeed',
    image: 'lscr.io/linuxserver/librespeed',
    status: 'paused',
    ports: ['81:80'],
    cpu: 0,
    memory: 18,
    network: 'paused',
    uptime: 'paused 2h',
    color: 'from-amber-500 to-yellow-400',
    sparkline: [10, 8, 7, 6, 8, 7, 6, 5, 6, 7, 6, 5],
  },
  {
    id: 'ct-homepage',
    name: 'homepage',
    image: 'ghcr.io/gethomepage/homepage',
    status: 'running',
    ports: ['3001:3000'],
    cpu: 6,
    memory: 22,
    network: '1.4 MB/s',
    uptime: '12 days',
    color: 'from-emerald-500 to-teal-400',
    sparkline: [8, 9, 8, 12, 10, 14, 13, 15, 14, 16, 15, 17],
  },
]

export const dockerImages = [
  { id: 'img-nginx', name: 'nginx', tag: 'latest', publisher: 'official', size: '187 MB', pulls: '1B+', description: 'High performance web server and reverse proxy.', accent: 'bg-emerald-500' },
  { id: 'img-postgres', name: 'postgres', tag: '16', publisher: 'official', size: '432 MB', pulls: '1B+', description: 'Reliable open source object-relational database.', accent: 'bg-blue-600' },
  { id: 'img-redis', name: 'redis', tag: '7-alpine', publisher: 'official', size: '42 MB', pulls: '1B+', description: 'In-memory data store used as cache, queue and broker.', accent: 'bg-red-500' },
  { id: 'img-jellyfin', name: 'jellyfin', tag: 'latest', publisher: 'community', size: '890 MB', pulls: '100M+', description: 'Media server for video, music and photos.', accent: 'bg-indigo-500' },
  { id: 'img-homeassistant', name: 'home-assistant', tag: 'stable', publisher: 'community', size: '1.2 GB', pulls: '100M+', description: 'Smart home automation platform.', accent: 'bg-cyan-500' },
  { id: 'img-mariadb', name: 'mariadb', tag: '11', publisher: 'official', size: '406 MB', pulls: '1B+', description: 'Community-developed relational database.', accent: 'bg-orange-500' },
]

export const dockerVolumes = [
  { id: 'vol-appdata', name: 'appdata', driver: 'local', mount: '/srv/yesnas/docker/appdata', used: 62, size: '512 GiB' },
  { id: 'vol-media', name: 'media', driver: 'bind', mount: '/srv/yesnas/media', used: 74, size: '2.8 TiB' },
  { id: 'vol-db', name: 'database', driver: 'local', mount: '/srv/yesnas/docker/db', used: 38, size: '256 GiB' },
]

export const dockerNetworks = [
  { id: 'net-bridge', name: 'bridge', driver: 'bridge', subnet: '172.17.0.0/16', containers: 4, status: 'online' },
  { id: 'net-media', name: 'media-stack', driver: 'bridge', subnet: '172.24.0.0/24', containers: 3, status: 'online' },
  { id: 'net-isolated', name: 'isolated-lab', driver: 'bridge', subnet: '172.30.0.0/24', containers: 1, status: 'offline' },
]
