import { Providers } from '@/components/layout/providers'
import { Inter } from 'next/font/google'
import type { Metadata, Viewport } from 'next'
import './globals.css'
import '@radix-ui/themes/styles.css'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'

import { Theme } from '@radix-ui/themes'
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
    { media: '(prefers-color-scheme: dark)', color: '#000000' },
  ],
}
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()
  const messages = await getMessages()

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Theme accentColor="blue" panelBackground="translucent">
            <Providers>{children}</Providers>
          </Theme>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
